# Use an appropriate base image for Meltano
FROM meltano/meltano:latest

# Set the working directory
WORKDIR /app

# Copy necessary files
COPY . /app
COPY ./requirements.txt .

# Install dependencies if needed
RUN pip install -r requirements.txt
RUN meltano install
# Don't allow changes to containerized project files
ENV MELTANO_PROJECT_READONLY 1

# Expose default port used by `meltano ui`
EXPOSE 5000

# Run the Meltano command to create products.csv
#CMD ["run", "tap-ex1","target-csv"]
