# Use an appropriate base image for FastAPI
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the FastAPI application files
COPY . /app


COPY ./requirements.txt .

# Install dependencies
RUN pip install -r requirements.txt
RUN pip install fastapi pandas

# Expose the port FastAPI will run on
EXPOSE 8000

# Run the FastAPI application
#CMD ["uvicorn", "run_api:app", "--host", "0.0.0.0", "--port", "8000"]
